### ISSUE TITLE
Deprecation warning for setup.py install method

### ISSUE THREAD

**Issue by mdgreenwald** [splitio/python-api#18]
```bash
pip install splitapiclient
```
`pip install` throws a deprecation warning:

> DEPRECATION: splitapiclient is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

**Comment by kleinjoshuaa** [comment]
Thanks @mdgreenwald - I plan on upgrading to `pyproject.toml` for the next release
